# Generated by Django 4.2.6 on 2023-11-10 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_blogs_created_at_alter_blogs_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blogs.topics'),
        ),
    ]
