# Generated by Django 4.2.6 on 2023-11-11 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_blogs_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='banner_img',
            field=models.ImageField(blank=True, null=True, upload_to='post_banner_img/'),
        ),
    ]
