# Generated by Django 4.2.6 on 2023-11-16 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_alter_blogs_banner_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
