# Generated by Django 4.2.6 on 2023-11-20 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_alter_like_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set(),
        ),
    ]
