# Generated by Django 4.2.6 on 2023-11-20 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0012_alter_like_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='report_blog',
            name='is_solved',
            field=models.BooleanField(default=False),
        ),
    ]
