# Generated by Django 4.2.6 on 2023-12-10 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0015_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='is_hide',
            field=models.BooleanField(default=False),
        ),
    ]
