# Generated by Django 4.2.6 on 2023-12-27 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0016_blogs_is_hide'),
    ]

    operations = [
        migrations.AddField(
            model_name='topics',
            name='desc',
            field=models.CharField(default='topic desc', max_length=100),
        ),
    ]
