# Generated by Django 4.2.6 on 2023-12-27 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0017_topics_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='topics',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='topic_img/'),
        ),
    ]
