# Generated by Django 4.2.6 on 2023-12-27 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0018_topics_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='blogs.topics'),
        ),
    ]
