# Generated by Django 4.2.6 on 2023-11-15 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumUserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_price', models.DecimalField(decimal_places=2, default=50, max_digits=10)),
                ('pan_number', models.CharField(max_length=10)),
                ('account_number', models.CharField(max_length=20)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Qualifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualifications', models.CharField(max_length=100)),
                ('premium_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.premiumuserinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Experiences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.CharField(max_length=200)),
                ('premium_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.premiumuserinfo')),
            ],
        ),
    ]
