# Generated by Django 4.2.6 on 2023-11-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_premiumuserinfo_qualifications_experiences'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumuserinfo',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
