# Generated by Django 4.2.6 on 2023-11-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_premiumuserinfo_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'user'), ('premium', 'Premium'), ('admin', 'Admin')], default='user', max_length=50),
        ),
    ]
