# Generated by Django 4.2.6 on 2023-11-16 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiences',
            name='experience',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='qualifications',
            name='qualifications',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
