# Generated by Django 4.2.6 on 2023-11-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_experiences_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumuserinfo',
            name='bank_name',
            field=models.CharField(default='sbi', max_length=100),
        ),
    ]
