# Generated by Django 4.2.6 on 2023-11-19 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiumuserinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='premiumuserinfo', to=settings.AUTH_USER_MODEL),
        ),
    ]
