# Generated by Django 4.2.6 on 2023-11-22 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_subscription_subscription_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='created_at',
            new_name='start_time',
        ),
        migrations.AddField(
            model_name='subscription',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
