# Generated by Django 4.2.6 on 2023-11-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_rename_created_at_subscription_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumuserinfo',
            name='sub_price_basic_mo',
            field=models.DecimalField(decimal_places=2, default=250, max_digits=10),
        ),
        migrations.AddField(
            model_name='premiumuserinfo',
            name='sub_price_std_yr',
            field=models.DecimalField(decimal_places=2, default=350, max_digits=10),
        ),
    ]
