# Generated by Django 4.2.6 on 2023-11-22 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_premiumuserinfo_sub_price_basic_mo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='premiumuserinfo',
            old_name='sub_price_basic_mo',
            new_name='sub_price_basic_yr',
        ),
    ]
