# Generated by Django 4.2.6 on 2023-11-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_rename_sub_price_basic_mo_premiumuserinfo_sub_price_basic_yr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='subscription_time',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscription_type',
            field=models.CharField(choices=[('basic_monthly', 'Basic_monthly'), ('basic_yearly', 'Basic_yearly'), ('standard_monthly', 'Standard_monthly'), ('standard_yearly', 'Standard_yearly')], max_length=30),
        ),
    ]
