# Generated by Django 4.2.6 on 2023-11-27 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_subscription_subscription_amount_wallet'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('subscriber', 'subscribed_to', 'subscription_type', 'subscription_amount', 'start_time')},
        ),
        migrations.AlterUniqueTogether(
            name='wallet',
            unique_together={('user_id', 'balance', 'recieved', 'created_at')},
        ),
    ]
