# Generated by Django 4.2.6 on 2023-11-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_subscription_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterUniqueTogether(
            name='wallet',
            unique_together={('user_id', 'recieved', 'created_at')},
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='balance',
        ),
    ]
