# Generated by Django 4.2.6 on 2023-11-27 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_user_wallet_balance_alter_wallet_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='wallet',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='wallet',
            name='recieved_from',
            field=models.ForeignKey(default=16, on_delete=django.db.models.deletion.CASCADE, related_name='recieved_transactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
