# Generated by Django 4.2.6 on 2023-12-06 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_report_issue'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('pre_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.premiumuserinfo')),
            ],
        ),
    ]
