# Generated by Django 4.2.6 on 2023-12-06 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_premiumrequests'),
    ]

    operations = [
        migrations.RenameField(
            model_name='premiumrequests',
            old_name='pre_id',
            new_name='premium',
        ),
    ]
