# Generated by Django 4.2.6 on 2023-12-06 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_experiences_premium_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumuserinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
