# Generated by Django 4.2.6 on 2023-11-30 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_message_thread_name_alter_message_message_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message_content',
            new_name='message',
        ),
    ]
